src/components/ActividadTabla/ActividadTabla.tsx, src/components/ActivityType/ActivityType.tsx, src/components/CheckerType/CheckerType.tsx, src/components/Checkpoint/Checkpoint.tsx, src/components/City/City.tsx, src/components/Company/Company.tsx, src/components/CriticityType/CriticityType.tsx, src/components/Division/Division.tsx, src/components/EmpleadoTabla/Empleado.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Position/Position.tsx, src/components/Process/Process.tsx, src/components/RiskMatrix/RiskMatrix.tsx, src/components/TipoTareas/TipoTareas.tsx
Agregar modal eliminar a todos los componentes
=> Agregar modal eliminar a todos los componentes

src/App.tsx, src/components/ActividadTabla/ActividadTabla.tsx, src/components/Actividades/Actividades.tsx, src/components/CheckerType/CheckerType.tsx, src/components/Checkpoint/Checkpoint.tsx, src/components/City/City.tsx, src/components/Company/Company.tsx, src/components/Criticidad/Criticidad.tsx, src/components/Division/Division.tsx, src/components/Menu/Menu.tsx, src/components/Position/Position.tsx, src/components/Process/Process.tsx, src/components/TipoTareas/TipoTareas.tsx, src/pages/ActividadesPage.tsx, src/pages/ActivitiesPage.tsx, src/pages/CriticityPage.tsx
Modificaciones pendientes modales, page y eliminar acciones
=> pendientes modales, page y eliminar acciones

src/components/Actividades/Actividades.tsx, src/components/Criticidad/Criticidad.tsx, src/components/Tareas/Tareas.tsx
actualizaciones titulos y rutas actividades, criticidad
=> titulos y rutas actividades, criticidad

package.json, src/components/Tareas/Tareas.tsx
avance tareas pendiente imagen
=> avance tareas

src/components/Checker/Checker.tsx
=> prueba rama checker

src/App.tsx, src/components/CheckerType/CheckerType.tsx, src/components/Menu/Menu.tsx, src/pages/CheckerPage.tsx, src/pages/CheckerType.tsx
-Se creo el Page de checherType
-Se corrigio la Ruta de Page de checker
-Se habilito el Menu de checker
-Se cambio el nombre de ruta de comprobaciones a jerarquia de control en App.tsx y Menu
=> rutas de checker y checkerType

src/components/Checker/Checker.tsx
-Se creo el componte checker
-crud ok
=> código ok en componente checker

src/components/Hazzard/Hazzard.tsx
-Se termino el crud hazzard agregando un select multiple de riesgos
=> hazzard crud ok

src/components/Division/Division.tsx, src/components/Position/Position.tsx, src/components/Tareas/Tareas.tsx
Modificaciones y actualizaciones Tareas y Posicion con pendientes
=> Modificaciones y actualizaciones Tareas y Posicion con pendientes

src/components/ActivitiesTable/ActivitiesTable.tsx, src/components/Checkpoint/Checkpoint.tsx, src/components/TipoTareas/TipoTareas.tsx
-Ajuste a los titulos acorde al sidebar
=> titulos de tablas modificadas

src/components/Menu/Menu.tsx
-Ajuste de titulo 
-Se comento Usuarios(no sale en el sidebar)
=> ajustes de titulos side-eliminación usuarios

src/components/ActividadTabla/ActividadTabla.tsx, src/components/City/City.tsx, src/components/Company/Company.tsx, src/components/Division/Division.tsx, src/components/Position/Position.tsx, src/components/Tareas/Tareas.tsx
-Ajustes modales iconos y titulos campos
=> ajustes modales

src/components/Checkpoint/Checkpoint.tsx, src/components/Tareas/Tareas.tsx
=> ajustes 2 modales

src/components/RiskMatrix/RiskMatrix.tsx
-Se cambio el estilo y se arreglo el modal
=> tabla riesgo ok

src/components/ActividadTabla/ActividadTabla.tsx, src/components/Actividades/Actividades.tsx, src/components/Checker/Checker.tsx, src/components/CheckerType/CheckerType.tsx, src/components/Checkpoint/Checkpoint.tsx, src/components/City/City.tsx, src/components/Company/Company.tsx, src/components/Criticidad/Criticidad.tsx, src/components/Division/Division.tsx, src/components/EmpleadoTabla/Empleado.tsx, src/components/Hazzard/Hazzard.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Process/Process.tsx, src/components/RiskMatrix/RiskMatrix.tsx, src/components/Tareas/Tareas.tsx, src/components/TipoTareas/TipoTareas.tsx
=> borrar console-logs

src/components/Menu/Menu.tsx
-Se elimino usuarios del sidebar
=> usuario eliminado de sidebar

src/components/Position/Position.tsx, src/components/Tareas/Tareas.tsx
Modificaciones de Cargos y Tareas Ok
=> Modificaciones de Cargos y Tareas Ok

src/components/CheckerType/CheckerType.tsx
-Se corrigió el problema de doble registro.
=> Corrección de Editar

src/components/CARPETA PRUEBA/CarpetaPrueba.tsx
=> carpeta y componente prueba

src/components/Actividades/Actividades.tsx
-Se corrigió el registro al editar.
=> Actividades(ActivityType) ok

src/components/ActividadTabla/ActividadTabla.tsx, src/components/Checkpoint/Checkpoint.tsx, src/components/Tareas/Tareas.tsx
Modificaciones Tareas - varios - Actividades
=> Modificaciones Tareas - varios - Actividades

src/components/Checkpoint/Checkpoint.tsx
=> Items terminado

src/components/ActividadTabla/ActividadTabla.tsx
=> Modificaciones actividad

src/components/ActividadTabla/ActividadTabla.tsx
modificaciones de actividades actualizadas
=> modificaciones de actividades actualizadas

src/components/Checker/Checker.tsx, src/components/DangerTable/DangerTableStyle.css, src/components/EncabezadoTabla/EncabezadoTablaStyle.css, src/components/Header/HeaderStyle.css, src/components/InfoCard/InfoCardStyle.css, src/components/Menu/MenuStyle.css, src/components/TableHeader/TableHeaderStyle.css
modificaciones de actualizacion borrar comentarios
=> modificaciones de actualizacion

src/components/Tareas/Tareas.tsx
modificaciones agregar sufijo para endpoint produccion  
https://testbackend-433922.uk.r.appspot.com/api/
=> modificaciones agregar sufijo para endpoint produccion

src/components/Menu/Menu.tsx, src/components/Menu/MenuStyle.css
-Versión final del sidebar MVP
=> Sidebar modificado versión final del MVP

src/App.tsx, src/components/Menu/Menu.tsx
=> cambios de rutas del sidebar

src/components/EncabezadoTabla/EncabezadoTablaStyle.css
-Se arreglo la cabecera con la tabla.
=> corrección encabezado de las tablas

src/components/Criticidad/Criticidad.tsx
-Se valido el campo name que sea solo entrada de números
=> validación número

src/components/DangerTable/DangerTableStyle.css, src/components/MatrizPeligro/MatrizPeligro.tsx, src/components/MatrizPeligro/MatrizPeligroStyle.css, src/pages/MatrizPeligroPage.tsx
-Se cambio el nombre en el componente, Page y App
-Se ajusto la cabecera a la tabla
=> Se cambio el nombre a Matriz de Peligro y ajuste de cabecera

src/components/VerificadorControl/VerificadorControl.tsx
-Se cambio titulo cabecera
-Se cambio Icono
-Se reviso el error al eliminar pero es de la bd
=> cambio de titulo y cambio de icono

src/components/Compañias/Compañias.tsx, src/components/Items/Items.tsx, src/components/JararquiaControl/JerarquiaControl.tsx, src/components/Menu/Menu.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Proceso/Proceso.tsx, src/components/TipoActividad/TipoActividad.tsx
-Cambio de iconos acuerdo al menu
=> Ajustes  modales

src/components/Cargo/Cargo.tsx, src/components/EncabezadoTabla/EncabezadoTablaStyle.css, src/components/Header/HeaderStyle.css, src/components/Tareas/Tareas.tsx
=> usabilidad tareas , cargos

src/components/VerificadorControl/VerificadorControl.tsx
-Se dejo tarea y items como number y null.
-Se creo una alerta para tareas ya seleccionadas.
=> Tabla verificiones de control ok

src/App.tsx, src/components/Menu/Menu.tsx, src/components/Planificacion/Planificacion.tsx, src/components/Tareas/Tareas.tsx, src/pages/PlanificacionPage.tsx, src/pages/PlanificadorActividadPage.tsx
modificaciones tareas, planificacion - última version develop
=> modificaciones tareas, planificacion

src/components/Planificacion/Planificacion.tsx
Planificacion pendiente eliminar
=> Planificacion pendiente eliminar

package-lock.json, package.json, src/App.tsx, src/components/Login/Login.tsx, src/components/Menu/Menu.tsx, src/components/Registro/Registro.css, src/components/Registro/Registro.tsx, src/pages/RegistroPage.tsx
Componentes login y register Pendientes endpoint
=> Componentes login y register

src/App.tsx, src/components/Colaboradores/Colaboradores.tsx, src/components/Header/Header.tsx, src/components/MatrizPeligro/MatrizPeligroStyle.css, src/components/TareaColaborador/TareaColaborador.css, src/components/TareaColaborador/TareaColaborador.tsx, src/pages/TareaColaboradorPage.tsx
-Se diseño la interfaz
-Se trajo la data a la tabla
=> Interfaz y funciones  listas  de tarea colaborador

src/components/Items/Items.tsx
-Se resolvió la caída de la interfaz .
=> ya no se cae la interfaz Items

src/components/Actividades/Actividades.tsx, src/components/Area/Area.tsx, src/components/Cargo/Cargo.tsx, src/components/Ciudad/Ciudad.tsx, src/components/Colaboradores/Colaboradores.tsx, src/components/Compañias/Compañias.tsx, src/components/Criticidad/Criticidad.tsx, src/components/Items/Items.tsx, src/components/JerarquiaControl/JerarquiaControl.tsx, src/components/Peligro/Peligro.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Planificacion/Planificacion.tsx, src/components/Proceso/Proceso.tsx, src/components/Riesgo/Riesgo.tsx, src/components/TareaColaborador/TareaColaborador.tsx, src/components/Tareas/Tareas.tsx, src/components/TipoActividad/TipoActividad.tsx, src/components/TipoTareas/TipoTareas.tsx, src/components/VerificadorControl/VerificadorControl.tsx
=> Implementación de Spinners de forma Global

src/components/Actividades/Actividades.tsx
=> actividades con spinner

src/components/Actividades/Actividades.tsx
=> Actividades Modificacion

src/components/Menu/Menu.tsx, src/components/Tareas/Tareas.tsx
-Se cambio el icono de editar y del menú al cerrar el login
=> iconos tarea y menu

src/App.tsx, src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.css, src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx, src/components/TareaColaborador/TareaColaborador.tsx, src/pages/ColaboradorEjecutarTareaPage.tsx
-Interfaz ok de Ejecutar tareas
=> respaldo de ejecutar tareas

src/components/TareaColaborador/TareaColaborador.css, src/components/TareaColaborador/TareaColaborador.tsx
-Interfaz y funcionalidades terminadas
=> Interfaz lista

src/components/Actividades/Actividades.tsx
Modificaciones de Actividad final - Testing final
=> Modificaciones de Actividad final

src/components/Actividades/Actividades.tsx, src/components/Area/Area.tsx, src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx, src/components/Colaboradores/Colaboradores.tsx, src/components/Peligro/Peligro.tsx, src/components/TareaColaborador/TareaColaborador.tsx, src/components/Tareas/Tareas.tsx, src/components/TipoTareas/TipoTareas.tsx
Actualizacion actividades Loading , Actualizado Develop - Testing
=> Actualizacion actividades Loading

src/components/Items/Items.tsx, src/components/Planificacion/Planificacion.tsx, src/components/Proceso/Proceso.tsx, src/components/Tareas/Tareas.tsx
Modificaciones de tareas, items, planificacion rut y loading
=> Modificaciones de tareas, items, planificacion rut y loading

src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx
-Modulo casi listo falta guardar ejecutar items y cargar imagen
=> modulo ejecutar items casi listo

src/App.tsx, src/components/Estados/Estados.tsx, src/components/Menu/Menu.tsx, src/pages/EstadosPage.tsx
=> Crear estados

src/components/Header/Header.tsx, src/components/Header/HeaderStyle.css
=> cerrar sesión

src/components/MatrizPeligro/MatrizPeligro.tsx, src/components/MatrizPeligro/MatrizPeligroStyle.css, src/pages/MatrizPeligroPage.tsx
=> se elimino submenu

src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx
=> Colaboradores ejecutar checkpoint no terminada

src/App.tsx, src/components/Menu/Menu.tsx
-Cambio de posición de los componentes Estados y Colaboradores"
-Se cambio en el App.tsx el lugar de Estados y también la ruta.
=> cambio de posición de componentes en el menu

src/components/Colaboradores/Colaboradores.tsx, src/components/Perfiles/Perfiles.tsx
-Se cambio alerta de back en Perfiles y colaboradores
-Se agrego Scroll a la tabla Colaboradores
=> cambio de mensaje de error en Perfil y Colaboradores

src/components/Actividades/Actividades.tsx, src/components/Area/Area.tsx, src/components/Ciudad/Ciudad.tsx, src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx, src/components/Compañias/Compañias.tsx, src/components/Criticidad/Criticidad.tsx, src/components/Estados/Estados.tsx, src/components/Items/Items.tsx, src/components/JerarquiaControl/JerarquiaControl.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Planificacion/Planificacion.tsx, src/components/Proceso/Proceso.tsx, src/components/TareaColaborador/TareaColaborador.tsx, src/components/TipoTareas/TipoTareas.tsx, src/components/Usuario/Usuario.tsx
=> scroll en el proyecto

src/components/Estados/Estados.tsx
-Se termino el componente Estados
=> Componente Estados listo

src/Routes/Routes.tsx
-se corrigió nombre carpeta Pages y ruta
=> corrección de carpeta Pages

src/Routes/Routes.tsx, src/components/Menu/Menu.tsx
-Componente Estados en el menú
=> Estado en Menu

src/Json/menuData.json, src/components/Menu/MenuStyle.css, src/components/Menu/SidebarMenu.css, src/components/Menu/SidebarMenu.tsx
=> modificacion menu-sidebar-css

src/App.tsx, src/Context/UserProvider.tsx, src/Interceptors/axiosConfig.tsx, src/Json/menuData.json, src/components/Header/Header.tsx, src/components/Menu/SidebarMenu.css, src/components/Menu/SidebarMenu.tsx
Modificaciones , actualizaciones , aumentar sesión
=> Modificaciones , actualizaciones , aumentar sesion

src/Context/UserProvider.tsx, src/Json/menuAdministrador.json, src/Models/User.tsx, src/components/Compañias/Compañias.tsx, src/components/Criticidad/Criticidad.tsx, src/components/JerarquiaControl/JerarquiaControl.tsx, src/components/Menu/Menu.tsx, src/components/Peligro/Peligro.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Proceso/Proceso.tsx, src/components/TipoActividad/TipoActividad.tsx
=> Features perfiles json

src/Json/menuAdministrador.json, src/components/Estados/Estados.tsx
=> Componente Estado Listo

src/components/Items/Items.tsx, src/components/Tareas/Tareas.tsx, src/components/VerificadorControl/VerificadorControl.tsx
verificador y checker solucionados
=> verificador y checker grabando

src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx
-Subida de Archivo
-Barra de progreso
=> Bugs subida archivo

src/components/Menu/SidebarMenu.tsx, src/components/VerificadorControl/VerificadorControl.tsx
modificacion verificador -checker , item graba y verificador graba
=> modificacion verificador -checker

src/components/Header/Header.tsx, src/components/Roles/Roles.tsx, src/components/Usuarios/Usuarios.tsx
=> modificacion menu

src/components/ColaboradorEjecutarTarea/ColaboradorEjecutarTarea.tsx
=> Bugs ejecutar tareas validaciones

src/Json/menuAdministrador.json, src/Routes/Routes.tsx, src/components/MatrizLegal/MatrizLegal.tsx, src/pages/MatrizLegalPage.tsx
-Se creo el componente y en el menú
=> tabla lista para traer datos

src/AppStyle.css, src/components/Actividades/Actividades.tsx, src/components/Area/Area.tsx, src/components/Cargo/Cargo.tsx, src/components/Ciudad/Ciudad.tsx, src/components/Colaboradores/Colaboradores.tsx, src/components/Compañias/Compañias.tsx, src/components/Criticidad/Criticidad.tsx, src/components/EncabezadoTabla/EncabezadoTablaStyle.css, src/components/Estados/Estados.tsx, src/components/Items/Items.tsx, src/components/JerarquiaControl/JerarquiaControl.tsx, src/components/MatrizPeligro/MatrizPeligro.tsx, src/components/Menu/SidebarMenu.css, src/components/Peligro/Peligro.tsx, src/components/Perfiles/Perfiles.tsx, src/components/Planificacion/Planificacion.css, src/components/Planificacion/Planificacion.tsx, src/components/Proceso/Proceso.tsx, src/components/Riesgo/Riesgo.tsx, src/components/Tareas/Tareas.tsx, src/components/TipoActividad/TipoActividad.tsx, src/components/TipoTareas/TipoTareas.tsx, src/components/VerificadorControl/VerificadorControl.tsx
=> actualizar scroll

package-lock.json, package.json, src/components/DoughnutChart/DoughnutChart.tsx, src/components/PlanificadorActividad/PlanificadorActividad.tsx, src/components/PlanificadorActividad/PlanificadorActividadStyle.css, src/components/TableHeader/TableHeaderStyle.css, src/pages/PlanificadorActividadPage.tsx
-Grafica en Chart.js 
-tabla con % de los progresos de las tareas
=> tabla y gráfica listas
